"""initial

Revision ID: 67fc2ff5aaf2
Revises:
Create Date: 2026-07-20 19:20:37.896396

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '67fc2ff5aaf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
